Tips = ([
    ".help for a list of commands.",
    "Goto #user-settings for changing your roles!",
    "There is 19 different level roles.",
    "Post suggestions in the suggestion channels.",
    "Change your user colors with .setcolor",
    "Do .profile to see your profile, duh!",
    "Tips are displayed here! Crazy right?",
    "Please don't lie about your age...",
    "Read channel topics!  If your confused...",
    "Razi needs to add more tips!",
    "Buy the XK Class role from the shop!!!  Has great channels.",
    "Daily's cap out after 365 days!",
    "Don't forget to claim your .daily!",
    "Coins are only created from user activity.",
    "The bot taxes everything, but also pays a lot of users.",
    "Mention council if ya need assistant with a dip-shit.",
])