token = "NTUwNDc0MTQ5MzMyNTE2ODgx.XHcrAA.ZgHJ_6yYFb9CTim_ElLTWrFwwX8"
prefix = "."
razisrealm_id = 689534383878701223
patreon = "https://www.patreon.com/Raziphel"
developer = 159516156728836097
bot_id = 896690181455892481

[database]
    user = "pterodactyl"
    password = "Pl3453Ch4n63M3!"
    database = "postgres"
    host = "172.18.0.3"

[channels]
    rules = 856449403173994536
    verify = 997346872622596136
    lounge = 807828084937850921
    adult_lounge = 928859827004928050
    furry_lounge = 928855284754038804
    greetings = 858574910280171550
    role_handler = 929353951818690660
    shop_handler = 946730953731100682
    leaderboard = 929093224545550336
    mines = 997415489527611432
    bot_log = 833960569941393438
    members_log = 833960606826364928
    currency_log = 858576957793239050
    interaction_log = 834245104411082762
    message_log = 833960665403883550
    mail_box = 860778768921526272
    archive = 997337911253024878
    kingussy = 991403616030167050

[roles]
    prisoner = 858923379315048488
    council = 891793700932431942

[emotes]
    silver = "<:Silver:994737895707525181>"
    gold = "<:Gold:994737893014773790>"
    emerald = "<:Emerald:994737891735511050>"
    diamond = "<:Diamond:994737890582069278>"
    ruby = "<:Ruby:994737896567357461>"
    sapphire = "<:Sapphire:994737897871782031>"
    amethyst = "<:Amethyst:994738216022319124> "
    crimson = "<:Crimson:994737894499569746>"


[messages]
    [errors]
        command_not_found = "I'm sorry but I don't believe that is a command?"
        missing_permissions = "I'm missing permissions to perform that command!"
        in_dms = "Sorry sweetie, that command can only be ran in my dms!"
        missing_arguments = "That command is missing stuff, do .help?"
        bad_arguments = "Thats the wrong way of running that command I'm afraid."
        missing_error = "Hmm, something went wrong and I'm not completely sure what."
        user_error = "Sorry but only a specific person can run that command."
        dev_error = "Only bot developers can run that command.  Weaklings can't handle it."
        guild_check = "Sorry, this command can not be run from this discord server."
        mod_check = "Sorry honey, only a moderator can run that command, stupid."
        admin_check = "You and I both know you don't have permission for that."
        error = "Uhhhh, something happened I don't know what to tell ya."